Add git ignore file for IDEA project files
aunueget/Karyotyping pull request #1
Opened 2017-03-29 21:02 UTC by semanticoverload

adding a ```.gitignore``` file so that inteliJ project files don't get added to the repo

2017-03-29 21:09 UTC, semanticoverload commented
@aunueget if you want to use inteliJ for this I can update so that the project related files are included in the repo and user specific files are ignored similar to [this gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)

2017-03-30 02:16 UTC, aunueget commented on .gitignore
> +.idea/
We may want to add some of these for java as well:
Reference:https://github.com/github/gitignore/blob/master/Java.gitignore
```
# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
hs_err_pid*
```

2017-03-30 02:18 UTC, aunueget requested changes
Do you think we should add some of these to the ignore?

2017-03-30 03:39 UTC, semanticoverload commented
Looks like the newer repo has a few more items. I prefer making changes as needed. I'm sure we will have other exceptions if we use it or edit it a little bit or if we add a build tool.

2017-03-30 20:11 UTC, closed without merging